### ISSUE TITLE
Launcher crash when child Process exits

### ISSUE THREAD

**Issue by vadi2** [alexanderkozlenko/dotnet-launcher#15]
### Summary

When a child process that reads a lot of stdout exits, the binary made with the launcher will crash.

### Artifacts
Test case: https://transfer.sh/iDBmS/ConsoleApp1.7z
+ https://github.com/Nictiz/Nictiz-STU3-Zib2017 (clone project)

### Reproducing
1. Adjust `scopePath` and `resourcePath` to the location of the Nictiz repository
1. Run `ConsoleApp1` in debugging environment (that is, without the launcher) - observe file with output is created successfully.
1. Publish application, run resulting launcher `.exe` - observe no file is created, crash happens instead:

```
An unhandled exception of type 'System.ExecutionEngineException' occurred in Unknown Module. occurred
```

I found this issue while trying to debug why https://github.com/vadi2/Hammer was crashing - turns out something is going wrong in the launcher, since `dotnet Hammer.dll` was working OK. Hope this test case helps find the problem!

**Comment by vadi2** [comment]
Note that the crash doesn't always happen, but it pretty frequently does. It might have to do with the size of the output generated.

**Comment by alexanderkozlenko** [comment]
@vadi2, thank you for the report! Could you please pack the test project ConsoleApp1 as a ZIP archive and attach directly to this thread? It seems the file is not available at the moment via the provided link.

**Comment by vadi2** [comment]
I've deleted the project since :( unless you have a copy, I don't have it anymore.

**Comment by alexanderkozlenko** [comment]
There is a new version of NuGet package 1.2.0 available which targets .NET Framework 4.5. I'm closing the issue at the moment; feel free to re-open it with a sample app if the issue will be still reproducible.
